server:
  port: 9210

#spring 相关配置
spring:
  application:
    name: consume-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    # 指定类型为我们自己的
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/com/blog/business/blog/**/*.xml

#将消费者注册到注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9300/eureka/
